/**
 * src/lib/cityRouteShards.ts
 *
 * Auto-generated by scripts/split-routes-by-city.js
 * Do not edit this file manually.
 */

import { Route } from './data';

export async function getCityRouteShard(citySlug: string): Promise<Route[]> {
  switch (citySlug) {
    case 'adityapur':
      return (await import('@/data/routes-by-city/adityapur.json')).default as unknown as Route[];
    case 'alipurduar':
      return (await import('@/data/routes-by-city/alipurduar.json')).default as unknown as Route[];
    case 'angul':
      return (await import('@/data/routes-by-city/angul.json')).default as unknown as Route[];
    case 'arambagh':
      return (await import('@/data/routes-by-city/arambagh.json')).default as unknown as Route[];
    case 'asansol':
      return (await import('@/data/routes-by-city/asansol.json')).default as unknown as Route[];
    case 'bagnan':
      return (await import('@/data/routes-by-city/bagnan.json')).default as unknown as Route[];
    case 'baharampur':
      return (await import('@/data/routes-by-city/baharampur.json')).default as unknown as Route[];
    case 'bakkhali':
      return (await import('@/data/routes-by-city/bakkhali.json')).default as unknown as Route[];
    case 'balasore':
      return (await import('@/data/routes-by-city/balasore.json')).default as unknown as Route[];
    case 'balurghat':
      return (await import('@/data/routes-by-city/balurghat.json')).default as unknown as Route[];
    case 'bankura':
      return (await import('@/data/routes-by-city/bankura.json')).default as unknown as Route[];
    case 'barasat':
      return (await import('@/data/routes-by-city/barasat.json')).default as unknown as Route[];
    case 'bardhaman':
      return (await import('@/data/routes-by-city/bardhaman.json')).default as unknown as Route[];
    case 'baripada':
      return (await import('@/data/routes-by-city/baripada.json')).default as unknown as Route[];
    case 'barrackpore':
      return (await import('@/data/routes-by-city/barrackpore.json')).default as unknown as Route[];
    case 'basirhat':
      return (await import('@/data/routes-by-city/basirhat.json')).default as unknown as Route[];
    case 'beldanga':
      return (await import('@/data/routes-by-city/beldanga.json')).default as unknown as Route[];
    case 'berhampur':
      return (await import('@/data/routes-by-city/berhampur.json')).default as unknown as Route[];
    case 'betla':
      return (await import('@/data/routes-by-city/betla.json')).default as unknown as Route[];
    case 'bhadrak':
      return (await import('@/data/routes-by-city/bhadrak.json')).default as unknown as Route[];
    case 'bhubaneswar':
      return (await import('@/data/routes-by-city/bhubaneswar.json')).default as unknown as Route[];
    case 'bishnupur':
      return (await import('@/data/routes-by-city/bishnupur.json')).default as unknown as Route[];
    case 'bodh-gaya':
      return (await import('@/data/routes-by-city/bodh-gaya.json')).default as unknown as Route[];
    case 'bokaro':
      return (await import('@/data/routes-by-city/bokaro.json')).default as unknown as Route[];
    case 'bolpur-shantiniketan':
      return (await import('@/data/routes-by-city/bolpur-shantiniketan.json')).default as unknown as Route[];
    case 'bongaon':
      return (await import('@/data/routes-by-city/bongaon.json')).default as unknown as Route[];
    case 'chaibasa':
      return (await import('@/data/routes-by-city/chaibasa.json')).default as unknown as Route[];
    case 'chakdah':
      return (await import('@/data/routes-by-city/chakdah.json')).default as unknown as Route[];
    case 'chandannagar':
      return (await import('@/data/routes-by-city/chandannagar.json')).default as unknown as Route[];
    case 'chatra':
      return (await import('@/data/routes-by-city/chatra.json')).default as unknown as Route[];
    case 'chilika':
      return (await import('@/data/routes-by-city/chilika.json')).default as unknown as Route[];
    case 'contai':
      return (await import('@/data/routes-by-city/contai.json')).default as unknown as Route[];
    case 'cooch-behar':
      return (await import('@/data/routes-by-city/cooch-behar.json')).default as unknown as Route[];
    case 'cuttack':
      return (await import('@/data/routes-by-city/cuttack.json')).default as unknown as Route[];
    case 'dalkhola':
      return (await import('@/data/routes-by-city/dalkhola.json')).default as unknown as Route[];
    case 'darjeeling':
      return (await import('@/data/routes-by-city/darjeeling.json')).default as unknown as Route[];
    case 'deoghar':
      return (await import('@/data/routes-by-city/deoghar.json')).default as unknown as Route[];
    case 'dhanbad':
      return (await import('@/data/routes-by-city/dhanbad.json')).default as unknown as Route[];
    case 'dhenkanal':
      return (await import('@/data/routes-by-city/dhenkanal.json')).default as unknown as Route[];
    case 'diamond-harbour':
      return (await import('@/data/routes-by-city/diamond-harbour.json')).default as unknown as Route[];
    case 'digha':
      return (await import('@/data/routes-by-city/digha.json')).default as unknown as Route[];
    case 'dooars':
      return (await import('@/data/routes-by-city/dooars.json')).default as unknown as Route[];
    case 'dum-dum':
      return (await import('@/data/routes-by-city/dum-dum.json')).default as unknown as Route[];
    case 'dumka':
      return (await import('@/data/routes-by-city/dumka.json')).default as unknown as Route[];
    case 'durgapur':
      return (await import('@/data/routes-by-city/durgapur.json')).default as unknown as Route[];
    case 'gangasagar':
      return (await import('@/data/routes-by-city/gangasagar.json')).default as unknown as Route[];
    case 'gaya':
      return (await import('@/data/routes-by-city/gaya.json')).default as unknown as Route[];
    case 'giridih':
      return (await import('@/data/routes-by-city/giridih.json')).default as unknown as Route[];
    case 'godda':
      return (await import('@/data/routes-by-city/godda.json')).default as unknown as Route[];
    case 'gopalpur':
      return (await import('@/data/routes-by-city/gopalpur.json')).default as unknown as Route[];
    case 'gumla':
      return (await import('@/data/routes-by-city/gumla.json')).default as unknown as Route[];
    case 'habra':
      return (await import('@/data/routes-by-city/habra.json')).default as unknown as Route[];
    case 'haldia':
      return (await import('@/data/routes-by-city/haldia.json')).default as unknown as Route[];
    case 'hazaribagh':
      return (await import('@/data/routes-by-city/hazaribagh.json')).default as unknown as Route[];
    case 'hooghly':
      return (await import('@/data/routes-by-city/hooghly.json')).default as unknown as Route[];
    case 'howrah':
      return (await import('@/data/routes-by-city/howrah.json')).default as unknown as Route[];
    case 'islampur':
      return (await import('@/data/routes-by-city/islampur.json')).default as unknown as Route[];
    case 'jalpaiguri':
      return (await import('@/data/routes-by-city/jalpaiguri.json')).default as unknown as Route[];
    case 'jamshedpur':
      return (await import('@/data/routes-by-city/jamshedpur.json')).default as unknown as Route[];
    case 'jamtara':
      return (await import('@/data/routes-by-city/jamtara.json')).default as unknown as Route[];
    case 'jeypore':
      return (await import('@/data/routes-by-city/jeypore.json')).default as unknown as Route[];
    case 'jhargram':
      return (await import('@/data/routes-by-city/jhargram.json')).default as unknown as Route[];
    case 'jharsuguda':
      return (await import('@/data/routes-by-city/jharsuguda.json')).default as unknown as Route[];
    case 'kakdwip':
      return (await import('@/data/routes-by-city/kakdwip.json')).default as unknown as Route[];
    case 'kalna':
      return (await import('@/data/routes-by-city/kalna.json')).default as unknown as Route[];
    case 'kalyani':
      return (await import('@/data/routes-by-city/kalyani.json')).default as unknown as Route[];
    case 'karimpur':
      return (await import('@/data/routes-by-city/karimpur.json')).default as unknown as Route[];
    case 'katwa':
      return (await import('@/data/routes-by-city/katwa.json')).default as unknown as Route[];
    case 'kharagpur':
      return (await import('@/data/routes-by-city/kharagpur.json')).default as unknown as Route[];
    case 'khunti':
      return (await import('@/data/routes-by-city/khunti.json')).default as unknown as Route[];
    case 'koderma':
      return (await import('@/data/routes-by-city/koderma.json')).default as unknown as Route[];
    case 'kolaghat':
      return (await import('@/data/routes-by-city/kolaghat.json')).default as unknown as Route[];
    case 'kolkata':
      return (await import('@/data/routes-by-city/kolkata.json')).default as unknown as Route[];
    case 'kolkata-airport':
      return (await import('@/data/routes-by-city/kolkata-airport.json')).default as unknown as Route[];
    case 'konark':
      return (await import('@/data/routes-by-city/konark.json')).default as unknown as Route[];
    case 'koraput':
      return (await import('@/data/routes-by-city/koraput.json')).default as unknown as Route[];
    case 'krishnanagar':
      return (await import('@/data/routes-by-city/krishnanagar.json')).default as unknown as Route[];
    case 'lalbagh':
      return (await import('@/data/routes-by-city/lalbagh.json')).default as unknown as Route[];
    case 'latehar':
      return (await import('@/data/routes-by-city/latehar.json')).default as unknown as Route[];
    case 'lohardaga':
      return (await import('@/data/routes-by-city/lohardaga.json')).default as unknown as Route[];
    case 'malda':
      return (await import('@/data/routes-by-city/malda.json')).default as unknown as Route[];
    case 'mandarmani':
      return (await import('@/data/routes-by-city/mandarmani.json')).default as unknown as Route[];
    case 'mayapur':
      return (await import('@/data/routes-by-city/mayapur.json')).default as unknown as Route[];
    case 'midnapore':
      return (await import('@/data/routes-by-city/midnapore.json')).default as unknown as Route[];
    case 'murshidabad':
      return (await import('@/data/routes-by-city/murshidabad.json')).default as unknown as Route[];
    case 'muzaffarpur':
      return (await import('@/data/routes-by-city/muzaffarpur.json')).default as unknown as Route[];
    case 'nabadwip':
      return (await import('@/data/routes-by-city/nabadwip.json')).default as unknown as Route[];
    case 'naihati':
      return (await import('@/data/routes-by-city/naihati.json')).default as unknown as Route[];
    case 'nalanda':
      return (await import('@/data/routes-by-city/nalanda.json')).default as unknown as Route[];
    case 'netarhat':
      return (await import('@/data/routes-by-city/netarhat.json')).default as unknown as Route[];
    case 'new-town-kolkata':
      return (await import('@/data/routes-by-city/new-town-kolkata.json')).default as unknown as Route[];
    case 'pakur':
      return (await import('@/data/routes-by-city/pakur.json')).default as unknown as Route[];
    case 'palamu':
      return (await import('@/data/routes-by-city/palamu.json')).default as unknown as Route[];
    case 'patna':
      return (await import('@/data/routes-by-city/patna.json')).default as unknown as Route[];
    case 'prayagraj':
      return (await import('@/data/routes-by-city/prayagraj.json')).default as unknown as Route[];
    case 'puri':
      return (await import('@/data/routes-by-city/puri.json')).default as unknown as Route[];
    case 'purulia':
      return (await import('@/data/routes-by-city/purulia.json')).default as unknown as Route[];
    case 'raiganj':
      return (await import('@/data/routes-by-city/raiganj.json')).default as unknown as Route[];
    case 'rajgir':
      return (await import('@/data/routes-by-city/rajgir.json')).default as unknown as Route[];
    case 'ramgarh':
      return (await import('@/data/routes-by-city/ramgarh.json')).default as unknown as Route[];
    case 'ranaghat':
      return (await import('@/data/routes-by-city/ranaghat.json')).default as unknown as Route[];
    case 'ranchi':
      return (await import('@/data/routes-by-city/ranchi.json')).default as unknown as Route[];
    case 'raniganj':
      return (await import('@/data/routes-by-city/raniganj.json')).default as unknown as Route[];
    case 'rayagada':
      return (await import('@/data/routes-by-city/rayagada.json')).default as unknown as Route[];
    case 'rourkela':
      return (await import('@/data/routes-by-city/rourkela.json')).default as unknown as Route[];
    case 'sahebganj':
      return (await import('@/data/routes-by-city/sahebganj.json')).default as unknown as Route[];
    case 'salt-lake-kolkata':
      return (await import('@/data/routes-by-city/salt-lake-kolkata.json')).default as unknown as Route[];
    case 'sambalpur':
      return (await import('@/data/routes-by-city/sambalpur.json')).default as unknown as Route[];
    case 'satragachhi':
      return (await import('@/data/routes-by-city/satragachhi.json')).default as unknown as Route[];
    case 'seraikela':
      return (await import('@/data/routes-by-city/seraikela.json')).default as unknown as Route[];
    case 'serampore':
      return (await import('@/data/routes-by-city/serampore.json')).default as unknown as Route[];
    case 'siliguri':
      return (await import('@/data/routes-by-city/siliguri.json')).default as unknown as Route[];
    case 'simdega':
      return (await import('@/data/routes-by-city/simdega.json')).default as unknown as Route[];
    case 'sundarbans':
      return (await import('@/data/routes-by-city/sundarbans.json')).default as unknown as Route[];
    case 'tamluk':
      return (await import('@/data/routes-by-city/tamluk.json')).default as unknown as Route[];
    case 'tarkeshwar':
      return (await import('@/data/routes-by-city/tarkeshwar.json')).default as unknown as Route[];
    case 'tatanagar':
      return (await import('@/data/routes-by-city/tatanagar.json')).default as unknown as Route[];
    case 'uluberia':
      return (await import('@/data/routes-by-city/uluberia.json')).default as unknown as Route[];
    case 'varanasi':
      return (await import('@/data/routes-by-city/varanasi.json')).default as unknown as Route[];
    default:
      return [];
  }
}
